### ISSUE TITLE
Translate sections (home, community, downloads)

### ISSUE THREAD

**Issue by rlaverde** [spyder-ide/website-spyder#21] opened 2016-08-20 03:15 UTC
We will have to wait https://github.com/goanpeca/spyder-website/pull/12  https://github.com/goanpeca/spyder-website/issues/15 and https://github.com/goanpeca/spyder-website/issues/20 before working in this issue

**Comment by CAM-Gerlach** [comment] 2023-09-28 02:11
This seems to essentially duplicate the same fundamental issue of spyder-ide/spyder-website#8 , providing translations of the website, and these pages no longer exist in their current form, so closing this as a duplicate of that for now.

**Closed as not planned by CAM-Gerlach** 2023-09-28 02:11 UTC
Labels: type:Feature
